name = "SyntheticPowerGridsPaper"
uuid = "e05e80bd-c7e7-49c6-8682-ba46473d0c11"
authors = ["buettner <buettner@pik-potsdam.de> and contributors"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
EmbeddedGraphs = "9c1af47c-29f5-11e9-0b47-9f5334384f20"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PowerDynamics = "cc46b21f-1b17-51c2-b642-af74c3d3a8be"
PowerGridNoise = "f331c818-237e-40db-bdde-b0d09ffa6503"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
SyntheticNetworks = "249d44c8-44e3-11e9-1b59-f5895c860273"
SyntheticPowerGrids = "614d5db8-069d-4715-bab2-9c1c938ea65a"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
